name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
                 
    - name: Restore dependencies
      run: dotnet restore dirs.proj
      
    - name: Build
      run: dotnet build --no-restore --configuration Release dirs.proj
      
    - name: Test
      run: dotnet test --logger GitHubActions dirs.proj

    - name: Capture Test Results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: TestResults
        path: TestResults/
